### ISSUE TITLE
this repo contains the MD17 and MD22 training details?

### ISSUE THREAD

**Issue by Eipgen** [microsoft/ViSNet#4]
Hi developer,
it's seems this repo can't use for energy and forces training under MD17 datasets, the examples I can find that is homo-lumo gap. Will you publish a new version about the energy and forces with MD17 datasets?

**Comment by Wys-LCC** [comment]
Dear Eipgen,

I apologize for the inconvenience. We have already pushed the code today, which should now support energy and forces training using MD17 datasets. We hope this will be helpful for your research.

We will be closing this issue for now, but please feel free to reopen it if you have any further questions or concerns.

Best regards,
Yusong

**Comment by Eipgen** [comment]
Thank you very much
